package com.example.farm;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.control.ChoiceBox;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

import java.io.IOException;

public class LivestockController {

    @FXML
    private TextField typeField;

    @FXML
    private TextField nameField;

    @FXML
    private TextField breedField;

    @FXML
    private TextField ageField;

    @FXML
    private ChoiceBox<String> healthStatusBox;

    @FXML
    private TableView<Animal> animalTable;

    @FXML
    private TableColumn<Animal, Integer> idColumn;

    @FXML
    private TableColumn<Animal, String> typeColumn;

    @FXML
    private TableColumn<Animal, String> nameColumn;

    @FXML
    private TableColumn<Animal, String> breedColumn;

    @FXML
    private TableColumn<Animal, Integer> ageColumn;

    @FXML
    private TableColumn<Animal, String> healthColumn;

    private final ObservableList<Animal> animalList = FXCollections.observableArrayList();

    public void initialize() {
        healthStatusBox.setItems(FXCollections.observableArrayList("Healthy", "Sick", "Injured"));
        healthStatusBox.setValue("Healthy");

        idColumn.setCellValueFactory(new PropertyValueFactory<>("id"));
        typeColumn.setCellValueFactory(new PropertyValueFactory<>("type"));
        nameColumn.setCellValueFactory(new PropertyValueFactory<>("name"));
        breedColumn.setCellValueFactory(new PropertyValueFactory<>("breed"));
        ageColumn.setCellValueFactory(new PropertyValueFactory<>("age"));
        healthColumn.setCellValueFactory(new PropertyValueFactory<>("healthStatus"));

        loadAnimals();
    }

    private void loadAnimals() {
        animalList.setAll(DatabaseHandler.getAnimals());
        animalTable.setItems(animalList);
    }

    @FXML
    protected void onAddClick() {
        try {
            String type = typeField.getText();
            String name = nameField.getText();
            String breed = breedField.getText();
            int age = Integer.parseInt(ageField.getText());
            String health = healthStatusBox.getValue();

            if (type.isEmpty() || name.isEmpty() || breed.isEmpty()) {
                System.out.println("Please fill all fields");
                return;
            }

            // ID is auto-generated by DB, pass 0
            Animal newAnimal = new Animal(0, type, name, breed, age, health);
            DatabaseHandler.addAnimal(newAnimal);
            loadAnimals();

            // Clear fields
            typeField.clear();
            nameField.clear();
            breedField.clear();
            ageField.clear();
            healthStatusBox.setValue("Healthy");

        } catch (NumberFormatException e) {
            System.out.println("Invalid age format");
        }
    }

    @FXML
    protected void onRemoveClick() {
        Animal selectedAnimal = animalTable.getSelectionModel().getSelectedItem();
        if (selectedAnimal != null) {
            DatabaseHandler.deleteAnimal(selectedAnimal.getId());
            loadAnimals();
        }
    }

    @FXML
    protected void onBackToHomeClick(ActionEvent event) throws IOException {
        FXMLLoader fxmlLoader = new FXMLLoader(HelloApplication.class.getResource("hello-view.fxml"));
        Parent root = fxmlLoader.load();
        Stage stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        stage.getScene().setRoot(root);
    }
}
